<?php

namespace IFCPHP\IFC4\Type;
use IFCPHP\IFC4 as IFC;

class IfcDistributionSystemEnum extends IFC\Common{

	static public $translationFR = 'Enumération des types de système de distribution';

	static public $params = [[
		'class' => 'Base\Value',
		'type' => 'object',
		'enum' => [
			'AIRCONDITIONING',
			'AUDIOVISUAL',
			'CHEMICAL',
			'CHILLEDWATER',
			'COMMUNICATION',
			'COMPRESSEDAIR',
			'CONDENSERWATER',
			'CONTROL',
			'CONVEYING',
			'DATA',
			'DISPOSAL',
			'DOMESTICCOLDWATER',
			'DOMESTICHOTWATER',
			'DRAINAGE',
			'EARTHING',
			'ELECTRICAL',
			'ELECTROACOUSTIC',
			'EXHAUST',
			'FIREPROTECTION',
			'FUEL',
			'GAS',
			'HAZARDOUS',
			'HEATING',
			'LIGHTING',
			'LIGHTNINGPROTECTION',
			'MUNICIPALSOLIDWASTE',
			'OIL',
			'OPERATIONAL',
			'POWERGENERATION',
			'RAINWATER',
			'REFRIGERATION',
			'SECURITY',
			'SEWAGE',
			'SIGNAL',
			'STORMWATER',
			'TELEPHONE',
			'TV',
			'VACUUM',
			'VENT',
			'VENTILATION',
			'WASTEWATER',
			'WATERSUPPLY',
			'USERDEFINED',
			'NOTDEFINED',
		],
	]];
}
/* DEFINITION
TYPE IfcDistributionSystemEnum = ENUMERATION OF
(AIRCONDITIONING
,AUDIOVISUAL
,CHEMICAL
,CHILLEDWATER
,COMMUNICATION
,COMPRESSEDAIR
,CONDENSERWATER
,CONTROL
,CONVEYING
,DATA
,DISPOSAL
,DOMESTICCOLDWATER
,DOMESTICHOTWATER
,DRAINAGE
,EARTHING
,ELECTRICAL
,ELECTROACOUSTIC
,EXHAUST
,FIREPROTECTION
,FUEL
,GAS
,HAZARDOUS
,HEATING
,LIGHTING
,LIGHTNINGPROTECTION
,MUNICIPALSOLIDWASTE
,OIL
,OPERATIONAL
,POWERGENERATION
,RAINWATER
,REFRIGERATION
,SECURITY
,SEWAGE
,SIGNAL
,STORMWATER
,TELEPHONE
,TV
,VACUUM
,VENT
,VENTILATION
,WASTEWATER
,WATERSUPPLY
,USERDEFINED
,NOTDEFINED);
END_TYPE;
*/
