<?php

namespace IFCPHP\IFC4\Type;
use IFCPHP\IFC4 as IFC;

class IfcElectricApplianceTypeEnum extends IFC\Common{

	static public $translationFR = 'Enumération des types d\'appareil électrique';

	static public $params = [[
		'class' => 'Base\Value',
		'type' => 'object',
		'enum' => [
			'DISHWASHER',
			'ELECTRICCOOKER',
			'FREESTANDINGELECTRICHEATER',
			'FREESTANDINGFAN',
			'FREESTANDINGWATERHEATER',
			'FREESTANDINGWATERCOOLER',
			'FREEZER',
			'FRIDGE_FREEZER',
			'HANDDRYER',
			'KITCHENMACHINE',
			'MICROWAVE',
			'PHOTOCOPIER',
			'REFRIGERATOR',
			'TUMBLEDRYER',
			'VENDINGMACHINE',
			'WASHINGMACHINE',
			'USERDEFINED',
			'NOTDEFINED',
		],
	]];
}
/* DEFINITION
TYPE IfcElectricApplianceTypeEnum = ENUMERATION OF
(DISHWASHER
,ELECTRICCOOKER
,FREESTANDINGELECTRICHEATER
,FREESTANDINGFAN
,FREESTANDINGWATERHEATER
,FREESTANDINGWATERCOOLER
,FREEZER
,FRIDGE_FREEZER
,HANDDRYER
,KITCHENMACHINE
,MICROWAVE
,PHOTOCOPIER
,REFRIGERATOR
,TUMBLEDRYER
,VENDINGMACHINE
,WASHINGMACHINE
,USERDEFINED
,NOTDEFINED);
END_TYPE;
*/
