<?php

namespace IFCPHP\IFC4\Type;
use IFCPHP\IFC4 as IFC;

class IfcEvaporativeCoolerTypeEnum extends IFC\Common{

	static public $translationFR = 'Enumération des types de refroidisseur évaporatif';

	static public $params = [[
		'class' => 'Base\Value',
		'type' => 'object',
		'enum' => [
			'DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER',
			'DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER',
			'DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER',
			'DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER',
			'DIRECTEVAPORATIVEAIRWASHER',
			'INDIRECTEVAPORATIVEPACKAGEAIRCOOLER',
			'INDIRECTEVAPORATIVEWETCOIL',
			'INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER',
			'INDIRECTDIRECTCOMBINATION',
			'USERDEFINED',
			'NOTDEFINED',
		],
	]];
}
/* DEFINITION
TYPE IfcEvaporativeCoolerTypeEnum = ENUMERATION OF
(DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER
,DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER
,DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER
,DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER
,DIRECTEVAPORATIVEAIRWASHER
,INDIRECTEVAPORATIVEPACKAGEAIRCOOLER
,INDIRECTEVAPORATIVEWETCOIL
,INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER
,INDIRECTDIRECTCOMBINATION
,USERDEFINED
,NOTDEFINED);
END_TYPE;
*/
