<?php

namespace IFCPHP\IFC4\Type;
use IFCPHP\IFC4 as IFC;

class IfcStairTypeEnum extends IFC\Common{

	static public $translationFR = 'Énumération des types d\'escalier';

	static public $params = [[
		'class' => 'Base\Value',
		'type' => 'object',
		'enum' => [
			'STRAIGHT_RUN_STAIR',
			'TWO_STRAIGHT_RUN_STAIR',
			'QUARTER_WINDING_STAIR',
			'QUARTER_TURN_STAIR',
			'HALF_WINDING_STAIR',
			'HALF_TURN_STAIR',
			'TWO_QUARTER_WINDING_STAIR',
			'TWO_QUARTER_TURN_STAIR',
			'THREE_QUARTER_WINDING_STAIR',
			'THREE_QUARTER_TURN_STAIR',
			'SPIRAL_STAIR',
			'DOUBLE_RETURN_STAIR',
			'CURVED_RUN_STAIR',
			'TWO_CURVED_RUN_STAIR',
			'USERDEFINED',
			'NOTDEFINED',
		],
	]];
}
/* DEFINITION
TYPE IfcStairTypeEnum = ENUMERATION OF
(STRAIGHT_RUN_STAIR
,TWO_STRAIGHT_RUN_STAIR
,QUARTER_WINDING_STAIR
,QUARTER_TURN_STAIR
,HALF_WINDING_STAIR
,HALF_TURN_STAIR
,TWO_QUARTER_WINDING_STAIR
,TWO_QUARTER_TURN_STAIR
,THREE_QUARTER_WINDING_STAIR
,THREE_QUARTER_TURN_STAIR
,SPIRAL_STAIR
,DOUBLE_RETURN_STAIR
,CURVED_RUN_STAIR
,TWO_CURVED_RUN_STAIR
,USERDEFINED
,NOTDEFINED);
END_TYPE;
*/
